# @package _global_

# example hyperparameter optimization of some experiment with Optuna:
# python train.py -m hparams_search=mnist_optuna experiment=example

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: random

# choose metric which will be optimized by Optuna
# make sure this is the correct name of some metric logged in lightning module!
optimized_metric: "val/acc_best"
task_name: "random_search"

# here we define Optuna hyperparameter search
# it optimizes for value returned from function with @hydra.main decorator
# docs: https://hydra.cc/docs/next/plugins/optuna_sweeper
hydra:
  mode: "MULTIRUN" # set hydra to multirun by default if this config is attached

  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper

    # storage URL to persist optimization results
    # for example, you can use SQLite if you set 'sqlite:///example.db'
    storage: null

    # name of the study to persist optimization results
    study_name: ${task_name}

    # number of parallel workers
    n_jobs: 1

    # 'minimize' or 'maximize' the objective
    direction: maximize

    # total number of runs that will be executed
    n_trials: 50

    # choose Optuna hyperparameter sampler
    # you can choose bayesian sampler (tpe), random search (without optimization), grid sampler, and others
    # docs: https://optuna.readthedocs.io/en/stable/reference/samplers.html
    sampler:
      _target_: optuna.samplers.RandomSampler
      seed: 1234

    # define hyperparameter search space
    params:
      model.net.num_hidden: range(128,4096)
      model.net.block_1_nb_filter: range(4,512)
      model.net.block_1_nb_layers: range(1,4)
      model.net.block_2_nb_filter: range(4,512)
      model.net.block_2_nb_layers: range(1,4)
      model.net.block_3_nb_filter: range(4,512)
      model.net.block_3_nb_layers: range(1,4)
      model.net.block_4_nb_filter: range(4,512)
      model.net.block_4_nb_layers: range(1,4)
      model.net.block_5_nb_filter: range(4,512)
      model.net.block_5_nb_layers: range(1,4)

